runtime: python37
env: standard
#servie: kakunin_kun
entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

#runtime_config:
#  python_version: 3

